services:
  paketnik-db:
    container_name: paketnik-mongo
    image: mongo:8.0
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=paketnik
      - MONGO_INITDB_ROOT_PASSWORD=paketnik123
      - MONGO_INITDB_DATABASE=paketnik-db
      - MONGODB_DB=paketnik-db
      - MONGODB_USER=paketnik
      - MONGODB_PASSWORD=paketnik123
    ports:
      - "27017:27017"

  paketnik-minio:
    container_name: paketnik-minio
    image: minio/minio
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server --console-address ":9001" /data
    volumes:
      - minio_data:/data

  paketnik-backend:
    container_name: paketnik-backend
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://paketnik:paketnik123@paketnik-db:27017/paketnik-db?authSource=admin
      - MINIO_ENDPOINT=http://paketnik-minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
    build:
      context: backend/.
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - paketnik-db
      - paketnik-minio

  paketnik-frontend:
    container_name: paketnik-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"

networks:
  paketnik-network:
    driver: bridge

volumes:
  minio_data:
