services:
  paketnik-db:
    container_name: paketnik-mongo
    image: mongo:8.0
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=paketnik
      - MONGO_INITDB_ROOT_PASSWORD=paketnik123
      - MONGO_INITDB_DATABASE=paketnik-db
      - MONGODB_DB=paketnik-db
      - MONGODB_USER=paketnik
      - MONGODB_PASSWORD=paketnik123
    ports:
      - "27018:27017"