spring:
  application:
    title: paketnik-back
    version: 0.0.1
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI}
      authentication-database: admin
      database: paketnik-db

server:
  port: 8081

app:
  flag-regex: ${FLAG_REGEX:}
  host-addr: ${HOST_ADDR:}
  start-time: ${START_TIME:}
  round-ticks: ${ROUND_TICKS:0}