spring:
  application:
    title: paketnik_back
    version: 0.0.1
  data:
    mongodb:
      uri: mongodb://paketnik:paketnik123@localhost:27018/paketnik-db?authSource=admin
      authentication-database: admin
      database: paketnik-db

server:
  port: 8081

app:
  flag-regex: "${FLAG_REGEX:}"
  host-addr: "${HOST_ADDR:}"
  start-time: "${START_TIME:}"
  round-ticks: "${ROUND_TICKS:0}"